project:
  type: book

book:
  title: "NSDF Tutorial: Using NSDF for End-to-End Analysis of Scientific Data"
  author: "Aashish Panta, Jack Marquez, Heberth Martinez, Amy Gooch, Giorgio Scorzell, Michela Taufer, Valerio Pascucci"
  date: "7/24/2024"
  cover-image: images/Logos.png
  chapters:
    - index.qmd
    - pages/001_prereq.qmd
    - pages/002_docker_codespaces.qmd
    - pages/004_appendix.qmd
    - pages/003_tutorials_notebook.qmd
    - pages/005_explore_subregion.qmd
    - pages/005_community_resources.qmd
    - pages/008_acknowledgements.qmd
    - pages/references.qmd
bibliography: references.bib
execute:
  echo: false
jupyter: python3
